### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by UsamaShaikh1** [BrianG13/FLEX#10]
I followed the training instructions as mentioned but encountered the following error
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\Admin\flex\train.py", line 222, in <module>
    train(config, args.resume)
  File "C:\Users\Admin\flex\train.py", line 139, in train
    trainer.train()
  File "C:\Users\Admin\flex\base\base_trainer.py", line 87, in train
    result = self._train_epoch(epoch)
  File "C:\Users\Admin\flex\trainer\multi_view_trainer.py", line 36, in _train_epoch
    for batch_idx, data in enumerate(self.data_loader):
  File "C:\Users\Admin\.conda\envs\flex\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\Admin\.conda\envs\flex\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\Users\Admin\.conda\envs\flex\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\Users\Admin\.conda\envs\flex\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0

**Comment by BrianG13** [comment]
Hi @UsamaShaikh1 ,

Can you check please the data has been loaded properly? 
Can you add here the entire logs?
